content:
  - name: snippets
    label: Snippets
    format: "json"
    filename: '{fields.slug}.json'
    type: collection
    path: content/snippets
    subfolders: true
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Snippet Title
        type: string
      - name: type
        label: Snippet Type
        type: string
      - name: slug
        label: Slug
        type: string
      - name: example
        label: Snippet Example
        type: rich-text
      - name: code
        label: Source Code
        type: rich-text